version: "3.5"
services:
  postgres:
    container_name: zapzup_postgres
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: zapzup_db_manager
      POSTGRES_USER: zapzup_db_manager
      POSTGRES_PASSWORD: zapzup_db_manager
    volumes:
      - ./resource/postgres-create-schema.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - zapzup

  zapzup:
    container_name: zapzup
    image: victorsantoss/zapzup_manager:2.0
    ports:
    - "8080:8080"
    command: java -Dspring.profiles.active=prod -jar zapzup-manager.jar -Xms512M -Xmx512M -XX:PermSize=256m -XX:MaxPermSize=512m
    working_dir: /app
    networks:
      - zapzup

networks:
  zapzup:
    driver: bridge