version: '3.7'

services:
  postgres:
    container_name: zapzup_postgres
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: zapzup_db_manager
      POSTGRES_USER: zapzup_db_manager
      POSTGRES_PASSWORD: zapzup_db_manager
    volumes:
      - ./postgres-create-schema.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - zapzup

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.9.1
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - zapzup

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: 7.9.1
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: ../logs.json
        target: /usr/share/logstash/logs/logs.json
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - zapzup
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.9.1
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - zapzup
    depends_on:
      - elasticsearch

networks:
  zapzup:
    driver: bridge

volumes:
  elasticsearch: