version: "3.5"
services:
  postgres:
    container_name: zapzup_postgres
    image: postgres:11.9
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: zapzup_db_manager
      POSTGRES_USER: zapzup_db_manager
      POSTGRES_PASSWORD: zapzup_db_manager
    volumes:
      - ./postgres-create-schema.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - zapzup

  zipkin:
    container_name: zapzup_zipkin
    image: openzipkin/zipkin:latest
    ports:
    - "9411:9411"
    networks:
      - zapzup

networks:
  zapzup:
    driver: bridge